<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Bank Demo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d73b258a-5bca-4816-99b2-13f587b1824c</testSuiteGuid>
   <testCaseLink>
      <guid>419047e9-066f-4b4a-972d-833073ead80b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Regist Page/TC Register Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b10d0866-4936-403c-90d6-28a455e5e84d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea6c6b48-cfdc-4eaf-9221-a467ef0fe315</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e3723c7-e654-4609-a45c-763be3037f72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2f6b920-571d-420c-a0aa-7269153a6680</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>317d3315-b0b1-457c-965d-eb3f68dde596</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Login Page/TC - New Login Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f50a3a67-c415-4a3b-9458-994279297e21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Dashboard/TC - Dashboard add acc for new regist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3591f4d9-36d2-4acf-ab48-10f3d7a2cef1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77b36dcf-c2de-4490-9d26-975b72c4c165</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc8c392e-b231-43f9-9c6a-1daae5e1b647</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Dashboard/TC - Dashboard verify account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>796d0373-9b82-4556-bade-783b06900501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdefe8bb-7f13-4383-82a3-db58c560497e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>954e2aef-1a5f-40b6-b78d-52851e0a7472</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Dashboard/TC - Dashboard add account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d90c2bc-2256-4911-a729-7ea2d3d70ad9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ff7db7a-9f46-4c61-82d0-70e29d4767c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2f0e580-d576-422b-aaec-a792a1ca8931</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC Dashboard/TC - Dashboard verify account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>796d0373-9b82-4556-bade-783b06900501</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdefe8bb-7f13-4383-82a3-db58c560497e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
